#!/usr/bin/env bash
# print the feilds from file etc/passwd in sentense


if [ -e "/etc/passwd" ]; then
while IFS=':' read -r USERNAME Pass userID GROUPID UserInf HOMEDIR SHELL ; do
    echo "The user $USERNAME is part of the $GROUPID gang, lives in $HOMEDIR and rides $SHELL. $userID's place is protected by the passcode $Pass, more info about the user here: $UserInf"
done < "/etc/passwd"
fi
