#!/usr/bin/env bash

# Copy the original hosts file to a temporary file
cp /etc/hosts ~/hosts.new

# Modify the temporary file to change localhost and add the new entry for facebook.com
sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new
sed -i '/localhost/ a 8.8.8.8 facebook.com' ~/hosts.new

# Replace the original hosts file with the modified version
sudo cp -f ~/hosts.new /etc/hosts
