#!/usr/bin/env bash
# Using what you did for task #1, make your fix short and sweet
sudo service nginx stop
sed -i 's/^user .*$/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen\s*80;/listen 8080;/g' /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
sudo service nginx start

